name: ai-klasifikasi-mata-uang-rupiah
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - scikit-learn=1.4.1.post1
  - ipykernel=6.29.3
  - pywin32=306
  - pip:
      - tensorflow==2.15.0
      - keras==2.15.0
      - imutils==0.5.4
      - opencv-python==4.9.0.80